name: kipsu_fi
description: My personal website
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  js: ^0.6.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  scissors: ^0.6.0
executables:
  rewrites: null
transformers:
- scissors:
    compiledCssExtension: replace
- angular2:
    platform_directives: 'package:angular2/common.dart#CORE_DIRECTIVES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
